# Generated by Django 5.0.4 on 2024-04-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='zip',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
